### ISSUE TITLE
server selection should skip inactive servers

### ISSUE THREAD

**Issue by paul-chambers** [nzbgetcom/nzbget#95]
_(cloned from [nzbget-ng issue nzbget-ng/nzbget-issues#15](https://github.com/nzbget-ng/nzbget-issues/issues/15), reported by @philon123)_

If I have a disabled priority 0 server and an enabled priority 1 server, currently nothing gets downloaded, it just hangs. I suppose it's waiting for the priority 0 server somehow? Obviously, that doesn't make sense, it should skip that server since it's disabled and move on to the priority 1 server immediately.

**Comment by luckedea** [comment]
Reviewed and it is something that is confusing indeed.
Help texts in the settings for level/priority and status are confusing.

If you have inactive high-priority server, and active lower-priority server, downloads are stuck.

Suggested scope:
1. Modify the behavior not to halt in this situation
2. Adjust help texts both for priority and for status of the server to make it unambiguous.

**Comment by luckedea** [comment]
Moving to v25, good first issue, maybe someone would help us with this :)

**Comment by ronrosenfeld** [comment]
@luckedea Does what you wrote mean this will not be fixed until V25? I just ran into a similar problem in that my priority 0 server source (which is active) was blocking me because of an expired credit card. I would have expected the download to switch to my priority 1 server but, instead, nothing happened and downloads were in the queue but nothing was being downloaded. I am running V24.3

**Comment by dnzbk** [comment]
Did you mark your server with priority 0 as optional?

**Comment by ronrosenfeld** [comment]
@dnzbk No, I didn't. And I see now that the documentation states that if the connection fails, it will not try a higher-level server, but rather wait for the connection to become available.  But also, all servers at the same level have the same priority.
My situation is that I need the primary server to be used first, going to the secondary server only if the primary server is either unable to retrieve, or if the primary server is down for a prolonged period of time (which is infrequent). 
Is there any way of accomplishing that? 
Or is setting the primary server to optional the only work-around?

Also, what happens if:
 - the primary server (priority 0) is marked optional
 - the primary server fails to connect
 - the secondary server (priority 1) begins downloading
 - the primary server becomes usable
Under that sequence, will the connection return to the primary server? Or does it stay with the secondary server until some trigger?

**Comment by dnzbk** [comment]
@ronrosenfeld 
Yes, the connection should return to the primary server.
But right now this functionality is pretty buggy. I already have two bug reports related to this feature, so be careful. 
#396 #300 
I even found another bug: if there are several servers with priority 0, and if only one of them is marked optional, the algorithm will not go to the next level if they are all failed.

Working on it.
